# Generated by Django 3.2.7 on 2021-10-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identifacion_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('delated_at', models.DateTimeField()),
            ],
        ),
    ]
