# Generated by Django 3.2.7 on 2021-10-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.user'),
        ),
    ]
