# Generated by Django 3.2.7 on 2021-10-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_session_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=4)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('delated_at', models.DateTimeField()),
            ],
        ),
    ]
